[CmdletBinding()]
param(
    [string]$RunName = "scroll_v_basic_acceptance"
)

$ErrorActionPreference = "Stop"
$repositoryRoot = (Resolve-Path -LiteralPath (Join-Path $PSScriptRoot "..\..\..\..")).Path
$samplePsd = Join-Path $repositoryRoot "Samples\Phase4_5\scroll_v_basic.psd"
$runFolder = Join-Path $repositoryRoot "AgentOrchestrator\runs\$RunName"

if (-not (Test-Path -LiteralPath $samplePsd -PathType Leaf)) {
    throw "找不到受版本控制的驗收樣本：$samplePsd"
}
if (Test-Path -LiteralPath $runFolder) {
    throw "驗收空間已存在，為避免沿用舊證據而停止：$runFolder"
}

$sourceFolder = Join-Path $runFolder "source"
$exportFolder = Join-Path $runFolder "export"
$artistFolder = Join-Path $runFolder "artist"
[System.IO.Directory]::CreateDirectory($sourceFolder) | Out-Null
[System.IO.Directory]::CreateDirectory($exportFolder) | Out-Null
[System.IO.Directory]::CreateDirectory($artistFolder) | Out-Null

$workingPsd = Join-Path $sourceFolder "scroll_v_basic.psd"
Copy-Item -LiteralPath $samplePsd -Destination $workingPsd

$request = [ordered]@{
    case_id = $RunName
    psd_path = $workingPsd
    psd_inspection_path = Join-Path $runFolder "psd_inspection.json"
    layout_json_path = Join-Path $exportFolder "layout.json"
    artist_asset_folder = $artistFolder
    exporter_asset_folder = Join-Path $exportFolder "Images"
    output_folder = $runFolder
    execution_mode = "analyze"
    semantics_approved = $false
    confirmed_semantics = @(
        "MainPage/List[SCROLL_V] is a vertical scroll group.",
        "Viewport and Content are generated by the deterministic Unity importer and must not be added to the PSD."
    )
}

$requestPath = Join-Path $runFolder "request.json"
$utf8WithoutBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText(
    $requestPath,
    ($request | ConvertTo-Json -Depth 8),
    $utf8WithoutBom
)

Write-Host "乾淨 PSD Agent 驗收空間已建立：$runFolder"
Write-Output $requestPath
